version: '3'

services:
  app:
    volumes:  
    - ./storage:/var/www/html/storage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - mynetwork
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
