version: '3.8'


services:

  # PHP Service
  php:
    build:
      context: .
      target: php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - my_network

  # Database server    
  database:
    image: mysql:8.0.35
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my_network

volumes:
  db-data: ~

networks:
  my_network: